---
- name: remove oracle base directory
  sudo: yes
  file:
    path: "{{ instantclient_base }}"
    state: absent

- name: remove link sqlplus
  sudo: yes
  file:
    dest: "{{ instantclient_bin_dir }}/sqlplus"
    state: absent

- name: remove sqlplus
  sudo: yes
  file:
    path: "{{ oracle_home }}/sqlplus"
    state: absent

- name: remove ORACLE_HOME environment variables
  sudo: yes
  lineinfile:
    dest: "{{ instantclient_env_file }}"
    regexp: "^export {{ item }}="
    state: absent
  with_items: "{{ instantclient_env_vars }}"
