---
- name: remove oracle base directory
  sudo: yes
  file:
    path: "{{ instantclient_base }}"
    state: absent

- name: remove link to sqlplus in my bin
  file:
    path: ~/bin/sqlplus
    state: absent

- name: remove ORACLE_HOME environment variables
  lineinfile:
    dest: "{{ instantclient_env_file }}"
    regexp: "^export {{ item }}="
    state: absent
  with_items: instantclient_env_vars
